server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started
 
eureka:
   instance:
    hostname: http://daxzg83339dns.eastus2.cloudapp.azure.com
   client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
   server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
